server:
  port: @init.port@
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/@init.dbName@?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: @init.dbPassword@
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    sql-script-encoding: UTF-8
  messages:
    basename: i18n/errors,i18n/messages
    fallback-to-system-locale: false
  resources:
    cache:
      cachecontrol:
        no-cache: true
  servlet:
    multipart:
      max-file-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

logbook:
  include: /api/**
  filter:
    enabled: true
  format:
    style: json

logging:
  config: classpath:logback-spring-dev.xml
  file:
    name: logs/@init.serviceName@.log
  level:
    com.dream: DEBUG
    org.zalando.logbook: TRACE

dream:
  framework:
    swagger:
      base-package: @init.package@
      title: @init.serviceTitle@
      ignored-parameter-types: com.dream.springframework.auth.token.model.TokenAuthUser
